### ISSUE TITLE
Episode 1 issues

### ISSUE THREAD

**Issue by bagder** [fossified/podcast#38]
I have the same problem with the newest episode but was able to play the pilot without issues.

_Originally posted by @kolaente in https://github.com/fossified/podcast/issues/24#issuecomment-1463400299_

**Comment by bagder** [comment]
@koalente, can you describe your issue with a few more words? Also what player do you use?

**Comment by andrew** [comment]
The latest episode simply doesn't show up in Overcast on iOS for me, only seeing the pilot episode there despite refreshing, restarting the app etc

**Comment by kolaente** [comment]
@bagder I'm using Podcast Republic on Android. When I try to download the episode it says "Wrong file received", when I try to play it without downloading it says "A playback error occured. Please try again later"

**Comment by hesa** [comment]
@kolaente 

> @bagder I'm using Podcast Republic on Android. When I try to download the episode it says "Wrong file received", when I try to play it without downloading it says "A playback error occured. Please try again later"

Are you using the RSS from us directly 
or are you (if that's possible I do not know) subscribed to one of the podcast providers (e.g. Spotify)?

**Comment by hesa** [comment]
@andrew 
> The latest episode simply doesn't show up in Overcast on iOS for me, only seeing the pilot episode there despite refreshing, restarting the app etc

Same as for @kolaente 

@kolaente

@bagder I'm using Podcast Republic on Android. When I try to download the episode it says "Wrong file received", when I try to play it without downloading it says "A playback error occured. Please try again later"

Are you using the RSS from us directly
or are you (if that's possible I do not know) subscribed to one of the podcast providers (e.g. Spotify)?

**Comment by kolaente** [comment]
@hesa I use the feed from you directly: https://pod.fossified.com/podcast.rss

**Comment by hesa** [comment]
> @hesa I use the feed from you directly: https://pod.fossified.com/podcast.rss

Hi @kolaente 

I installed **Republic Podcast** version **23.3.2R** via Google Play Store (or what ever it is called) since I could not find it at [f-droid.org](https://f-droid.org/en/) and it works nicely here for me. I tested:
* adding the podcast URL
* playing roughly ten seconds per episode (starting with pilot)

Guessing my way forward:

* Does the app cache some data (e.g. that we had an ogg file for a while for the Pilot)?

* Try remove podcast and re-add it?

**Comment by andrew** [comment]
@hesa I had searched for "fossified" in Overcast and added it, I just tried deleting it and re-adding it and it's worked now, previously it showed the source as fossified.github.io but now shows it as pod.fossified.com, so fixed for me 👍

**Comment by kolaente** [comment]
> Does the app cache some data (e.g. that we had an ogg file for a while for the Pilot)?
> Try remove podcast and re-add it?

I don't know, I tried clearing caches and re-adding it but no luck. The really wired thing for me is how the pilot works but the first real episode doesn't.

Will try to talk to the developers of the app, maybe they spot something.

**Comment by kolaente** [comment]
Now I refreshed the podcast and the episode shows up twice? The one on top is the one I can't play but the one below that seems to work fine.

![Screenshot_20230310-143849_Podcast Republic.png](https://user-images.githubusercontent.com/13721712/224330582-71179a15-c98f-46ea-8850-c7fec18070e7.png)

Not sure what the problem here is but it looks like it works now.

**Comment by henrik-sandklef-intel** [comment]
> 

Can we blame this on today being a Friday almost 13th?

Anyhow, my guess is that our initial quagmire configurations of this podcast is the root of the problem. Hopefully these problems will slowly go away.

Closing the issue
